import type { TuiState } from "../state";

export function makeTuiState(overrides: Partial<TuiState> = {}): TuiState {
  return {
    cwd: null,
    gitBranch: null,
    gitDirty: false,
    version: "",
    installedTeams: null,
    teamId: null,
    sessionName: null,
    leaderAgentId: null,
    agents: new Map(),
    focusedAgentId: null,
    teamCursorAgentId: null,
    interruptedAgentId: null,
    nextEntrySeq: 0,
    transientMessage: null,
    errorBanner: null,
    thinkingExpanded: false,
    toolCardsExpanded: false,
    teamPanelVisible: false,
    helpPanelVisible: false,
    kanbanView: "hidden",
    kanbanBoard: [],
    kanbanCursor: null,
    kanbanExpanded: false,
    kanbanEdit: null,
    kanbanEditField: "content",
    pendingQuit: false,
    editorText: "",
    editorCursorAtStart: true,
    ...overrides,
  };
}
